### PR TITLE
Task note

### PR DESCRIPTION
**Pull request by bogdal**
This PR adds ability to add task note.
You just need to start with `//` at the end of the phrase, and then write a note.

zrzut ekranu 2017-11-01 o 19 31 31
zrzut ekranu 2017-11-01 o 19 47 36

### CODE REVIEW

**Comment by idpaterson** [comment]
This looks great, would you please rebase your pull request to develop so that I can roll this into a release?

**Comment by idpaterson** [comment]
The only concern I have with the code is the inclusion of `:` in the pattern:
```
SLASHES_PATTERN = re.compile(r'(?:^|[\s:])(//)(.*)$', re.DOTALL)
```

I think that would cause a link in the task to be split into a note, for example would the following result in a task titled "buy tickets https" and a note "buy.tix/23873487"?

> wl buy tickets https://buy.tix/23873487

**Comment by bogdal** [comment]
Good catch ⚡️ I will improve regex.

**Comment by idpaterson** [comment]
That will work, thanks!

**Comment by idpaterson** [comment]
@bogdal thanks for your work, I think many will appreciate it! Please try the [0.7.0-alpha release](https://github.com/idpaterson/alfred-wunderlist-workflow/releases/tag/0.7.0-alpha) to confirm that my build process still works before I publish the release 😄

**Comment by bogdal** [comment]
@idpaterson 0.7.0-alpha release works like a charm 👍

**Comment by idpaterson** [comment]
Perfect, thanks.

**Pull request merged**
